name: scijava
channels:
  - damianavila82
  - conda-forge
  - hanslovsky
dependencies:
  - python
  - numpy
  - scikit-image
  - matplotlib
  - imglib2-imglyb
  - beakerx
  - scijava-jupyter-kernel
  - rise
